image: docker:24.0.5

stages:
  - build

services:
  - docker:24.0.5-dind

variables:
  DOCKER_BUILDKIT: 1
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build:
  stage: build
  script:
    # Extract AAS version from .env
    - export AAS_VERSION=$(grep '^AAS_VERSION=' .env | cut -d'=' -f2-)
    - echo "AAS_VERSION is $AAS_VERSION"

    # Attempt to pull latest image for caching
    - docker pull "$CI_REGISTRY_IMAGE:latest" || true

    # Create and use buildx instance
    - docker buildx create --use

    # Build and push multi-arch image with appropriate tags
    - >
      docker buildx build --platform linux/amd64,linux/arm64 \
        --pull \
        --build-arg http_proxy=$http_proxy \
        --build-arg https_proxy=$https_proxy \
        --build-arg no_proxy=$no_proxy \
        --build-arg AAS_VERSION=$AAS_VERSION \
        --build-arg VCS_REF=$CI_COMMIT_SHA \
        --build-arg VCS_URL=$CI_PROJECT_URL \
        --cache-from "$CI_REGISTRY_IMAGE:latest" \
        --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" \
        $( [[ "$CI_COMMIT_BRANCH" == "main" ]] && echo --tag "$CI_REGISTRY_IMAGE:latest" ) \
        $( [[ -n "$CI_COMMIT_TAG" ]] && echo --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" ) \
        --push .

    # Prune builder cache and intermediates (optional, but cleans runner)
    - docker builder prune -f
    - docker image prune -f
